services:
  dotnet-server:
    build:
      context: .
      dockerfile: examples/servers/dotnet/Dockerfile
  go-server:
    build:
      context: .
      dockerfile: examples/servers/go/Dockerfile
  java-server:
    build:
      context: .
      dockerfile: examples/servers/java/Dockerfile
  python-server:
    build:
      context: .
      dockerfile: examples/servers/python/Dockerfile
  dotnet-client:
    build:
      context: .
      dockerfile: examples/clients/dotnet/Dockerfile
  go-client:
    build:
      context: .
      dockerfile: examples/clients/go/Dockerfile
  java-client:
    build:
      context: .
      dockerfile: examples/clients/java/Dockerfile
  python-client:
    build:
      context: .
      dockerfile: examples/clients/python/Dockerfile
