package contract

import (
	"encoding/json"
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"strings"
)

// Generate binds the reusable runtime adapter to a build's contract lock.
// Each output module/package represents one service contract.
func Generate(s *Snapshot, language, packageName string) ([]byte, error) {
	if err := validateGeneration(s); err != nil {
		return nil, err
	}
	quote := func(value string) string { b, _ := json.Marshal(value); return string(b) }
	api, version, service := quote(s.API), quote(s.Version), quote(s.Service.Name)
	switch language {
	case "typescript":
		if packageName != "" {
			return nil, fmt.Errorf("--package is not used for TypeScript")
		}
		return TypeScript(s)
	case "python":
		if packageName != "" {
			return nil, fmt.Errorf("--package is not used for Python")
		}
		return []byte(fmt.Sprintf(`# Code generated by proto-contract from a contract lock. DO NOT EDIT.
from proto_contract import ContractClientInterceptor as _ContractClientInterceptor
from proto_contract import ContractServerInterceptor as _ContractServerInterceptor

API = %s
VERSION = %s
SERVICE = %s

class ClientInterceptor(_ContractClientInterceptor):
    """Client interceptor bound to this module's generated contract."""
    def __init__(self):
        super().__init__(API, VERSION)

class ServerInterceptor(_ContractServerInterceptor):
    """Server interceptor bound to this service's generated contract."""
    def __init__(self):
        super().__init__(API, VERSION)

    def intercept_service(self, continuation, handler_call_details):
        if not handler_call_details.method.startswith("/" + SERVICE + "/"):
            return continuation(handler_call_details)
        return super().intercept_service(continuation, handler_call_details)
`, api, version, service)), nil
	case "go":
		if packageName == "" {
			packageName = "contractgen"
		}
		if !token.IsIdentifier(packageName) || packageName == "_" {
			return nil, fmt.Errorf("invalid Go package %q", packageName)
		}
		return format.Source([]byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
package %s

import (
  "context"
  "strings"
  "github.com/dunkymole/proto-contract/runtimes/go/protocontract"
  "google.golang.org/grpc"
)

const API = %s
const Version = %s
const Service = %s

// ClientInterceptor returns an interceptor bound to this package's generated contract.
func ClientInterceptor() grpc.UnaryClientInterceptor {
  return protocontract.UnaryClient(API, Version)
}

// ServerInterceptor enforces this service's contract and leaves other services to their own interceptor.
func ServerInterceptor() grpc.UnaryServerInterceptor {
  enforce := protocontract.UnaryServer(API, Version)
  return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
    if !strings.HasPrefix(info.FullMethod, "/" + Service + "/") {
      return handler(ctx, req)
    }
    return enforce(ctx, req, info, handler)
  }
}
`, packageName, api, version, service)))
	case "java":
		if packageName == "" {
			packageName = "protocontract.generated"
		}
		if err := validatePackage(packageName, language); err != nil {
			return nil, err
		}
		return []byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
package %s;

import io.github.dunkymole.protocontract.ContractClientInterceptor;
import io.github.dunkymole.protocontract.ContractServerInterceptor;

public final class Contract {
  public static final String API = %s;
  public static final String VERSION = %s;
  public static final String SERVICE = %s;

  private Contract() {}

  public static ContractClientInterceptor clientInterceptor() {
    return new ContractClientInterceptor(API, VERSION);
  }

  public static ContractServerInterceptor serverInterceptor() {
    return new ContractServerInterceptor(API, VERSION);
  }
}
`, packageName, api, version, service)), nil
	case "dotnet":
		if packageName == "" {
			packageName = "ProtoContract.Generated"
		}
		if err := validatePackage(packageName, language); err != nil {
			return nil, err
		}
		return []byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
namespace %s;

public static class Contract
{
    public const string Api = %s;
    public const string Version = %s;
    public const string Service = %s;

    public static global::ProtoContract.ContractClientInterceptor ClientInterceptor() =>
        new global::ProtoContract.ContractClientInterceptor(Api, Version);

    public sealed class ServerInterceptor : global::ProtoContract.ContractServerInterceptor
    {
        public ServerInterceptor() : base(Api, Version) { }
    }
}
`, packageName, api, version, service)), nil
	default:
		return nil, fmt.Errorf("unsupported language %q", language)
	}
}

func validateGeneration(s *Snapshot) error {
	if s == nil || s.Format != 1 {
		return fmt.Errorf("unsupported contract lock format")
	}
	// These identifiers become ASCII gRPC metadata and protobuf service names.
	if !regexp.MustCompile(`^[!-?A-~]+$`).MatchString(s.API) ||
		!regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$`).MatchString(s.Service.Name) {
		return fmt.Errorf("lock requires a valid API identifier and service name")
	}
	if !regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$`).MatchString(s.Version) {
		return fmt.Errorf("version must be MAJOR.MINOR.PATCH")
	}
	_, err := NextVersion(s.Version, None)
	return err
}

func validatePackage(name, language string) error {
	// Shared subset of Java package and C# namespace identifiers.
	keywords := " abstract as assert base bool boolean break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false final finally fixed float for foreach goto if implements implicit import in instanceof int interface internal is lock long namespace native new null object operator out override package params private protected public readonly ref return sbyte sealed short sizeof stackalloc static strictfp string struct super switch synchronized this throw throws transient true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while _ "
	for _, part := range strings.Split(name, ".") {
		if !regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`).MatchString(part) || strings.Contains(keywords, " "+part+" ") {
			return fmt.Errorf("invalid %s package/namespace %q", language, name)
		}
	}
	return nil
}
