package contract

import (
	"encoding/json"
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"strconv"
	"strings"
)

// Generate binds the reusable runtime adapter to a build's contract lock.
// Each output module/package represents one service contract.
func Generate(s *Snapshot, language, packageName string) ([]byte, error) {
	if err := validateGeneration(s); err != nil {
		return nil, err
	}
	quote := func(value string) string { b, _ := json.Marshal(value); return string(b) }
	api, version, service := quote(s.API), quote(s.Version), quote(s.Service.Name)
	switch language {
	case "typescript":
		if packageName != "" {
			return nil, fmt.Errorf("--package is not used for TypeScript")
		}
		return TypeScript(s)
	case "python":
		if packageName != "" {
			return nil, fmt.Errorf("--package is not used for Python")
		}
		return []byte(fmt.Sprintf(`# Code generated by proto-contract from a contract lock. DO NOT EDIT.
from proto_contract import ContractClientInterceptor as _ContractClientInterceptor
from proto_contract import ContractServerInterceptor as _ContractServerInterceptor
from proto_contract import StrictServerInterceptor as _StrictServerInterceptor

API = %s
VERSION = %s
SERVICE = %s

class ClientInterceptor(_ContractClientInterceptor):
    """Client interceptor bound to this module's generated contract."""
    def __init__(self):
        super().__init__(API, VERSION, SERVICE)

class ServerInterceptor(_ContractServerInterceptor):
    """Server interceptor bound to this service's generated contract."""
    def __init__(self):
        super().__init__(API, VERSION, SERVICE)

    def intercept_service(self, continuation, handler_call_details):
        if not handler_call_details.method.startswith("/" + SERVICE + "/"):
            return continuation(handler_call_details)
        return super().intercept_service(continuation, handler_call_details)

def StrictServerInterceptor(exemptions=()):
    return _StrictServerInterceptor({SERVICE: ServerInterceptor()}, exemptions)
`, api, version, service)), nil
	case "go":
		if packageName == "" {
			packageName = "contractgen"
		}
		if !token.IsIdentifier(packageName) || packageName == "_" {
			return nil, fmt.Errorf("invalid Go package %q", packageName)
		}
		return format.Source([]byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
package %s

import (
  "github.com/dunkymole/proto-contract/runtimes/go/protocontract"
  "google.golang.org/grpc"
)

const API = %s
const Version = %s
const Service = %s

// Client returns validated, service-scoped client hooks for every RPC shape.
func Client() *protocontract.Client {
  client, err := protocontract.NewClient(API, Version, Service)
  if err != nil { panic(err) }
  return client
}
func ClientInterceptor() grpc.UnaryClientInterceptor { return Client().Unary() }
func ClientStreamInterceptor() grpc.StreamClientInterceptor { return Client().Stream() }

// ServerInterceptor enforces this service's contract and leaves other services to their own interceptor.
func Server() *protocontract.Server { server, err := protocontract.NewServer(API, Version, Service); if err != nil { panic(err) }; return server }
func ServerInterceptor() grpc.UnaryServerInterceptor { return Server().Unary() }
func ServerStreamInterceptor() grpc.StreamServerInterceptor { return Server().Stream() }
func StrictServer(exemptions ...string) (*protocontract.StrictServer, error) { return protocontract.NewStrictServer(map[string]*protocontract.Server{Service: Server()}, exemptions) }
`, packageName, api, version, service)))
	case "java":
		if packageName == "" {
			packageName = "protocontract.generated"
		}
		if err := validatePackage(packageName, language); err != nil {
			return nil, err
		}
		return []byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
package %s;

import io.github.dunkymole.protocontract.ContractClientInterceptor;
import io.github.dunkymole.protocontract.ContractServerInterceptor;
import io.github.dunkymole.protocontract.StrictServerInterceptor;
import java.util.Map;
import java.util.Set;

public final class Contract {
  public static final String API = %s;
  public static final String VERSION = %s;
  public static final String SERVICE = %s;

  private Contract() {}

  public static ContractClientInterceptor clientInterceptor() {
    return new ContractClientInterceptor(API, VERSION, SERVICE);
  }

  public static ContractServerInterceptor serverInterceptor() {
    return new ContractServerInterceptor(API, VERSION, SERVICE);
  }

  public static StrictServerInterceptor strictServerInterceptor(String... exemptions) {
    return new StrictServerInterceptor(Map.of(SERVICE, serverInterceptor()), Set.of(exemptions));
  }
}
`, packageName, api, version, service)), nil
	case "dotnet":
		if packageName == "" {
			packageName = "ProtoContract.Generated"
		}
		if err := validatePackage(packageName, language); err != nil {
			return nil, err
		}
		return []byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
namespace %s;

public static class Contract
{
    public const string Api = %s;
    public const string Version = %s;
    public const string Service = %s;

    public static global::ProtoContract.ContractClientInterceptor ClientInterceptor() =>
        new global::ProtoContract.ContractClientInterceptor(Api, Version, Service);

    public sealed class ServerInterceptor : global::ProtoContract.ContractServerInterceptor
    {
        public ServerInterceptor() : base(Api, Version, Contract.Service) { }
    }

    public static global::ProtoContract.StrictServerInterceptor StrictServerInterceptor(params string[] exemptions) =>
        new global::ProtoContract.StrictServerInterceptor(
            new global::System.Collections.Generic.Dictionary<string, global::ProtoContract.ContractServerInterceptor> { [Service] = new ServerInterceptor() }, exemptions);
}
`, packageName, api, version, service)), nil
	default:
		return nil, fmt.Errorf("unsupported language %q", language)
	}
}

func validateGeneration(s *Snapshot) error {
	if s == nil || s.Format != 2 {
		return fmt.Errorf("unsupported contract lock format")
	}
	// These identifiers become ASCII gRPC metadata and protobuf service names.
	if !regexp.MustCompile(`^[A-Za-z0-9._:/-]{1,64}$`).MatchString(s.API) ||
		!regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$`).MatchString(s.Service.Name) {
		return fmt.Errorf("lock requires a valid API identifier and service name")
	}
	if !regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$`).MatchString(s.Version) {
		return fmt.Errorf("version must be MAJOR.MINOR.PATCH")
	}
	for _, part := range strings.Split(s.Version, ".") {
		component, err := strconv.ParseUint(part, 10, 32)
		if err != nil || component > 2147483647 {
			return fmt.Errorf("version components must be between 0 and 2147483647")
		}
	}
	_, err := NextVersion(s.Version, None)
	return err
}

func validatePackage(name, language string) error {
	// Shared subset of Java package and C# namespace identifiers.
	keywords := " abstract as assert base bool boolean break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false final finally fixed float for foreach goto if implements implicit import in instanceof int interface internal is lock long namespace native new null object operator out override package params private protected public readonly ref return sbyte sealed short sizeof stackalloc static strictfp string struct super switch synchronized this throw throws transient true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while _ "
	for _, part := range strings.Split(name, ".") {
		if !regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`).MatchString(part) || strings.Contains(keywords, " "+part+" ") {
			return fmt.Errorf("invalid %s package/namespace %q", language, name)
		}
	}
	return nil
}
