package contract

import (
	"encoding/json"
	"fmt"
)

// TypeScript generates a self-contained client interceptor from a contract lock.
func TypeScript(s *Snapshot) ([]byte, error) {
	if err := validateGeneration(s); err != nil {
		return nil, err
	}
	quote := func(value string) string { b, _ := json.Marshal(value); return string(b) }
	return []byte(fmt.Sprintf(`// Code generated by proto-contract from a contract lock. DO NOT EDIT.
import { Code, ConnectError, type Interceptor } from "@connectrpc/connect";

export const contract = {
  api: %s,
  version: %s,
  service: %s,
} as const;

/** Install per generated client with grpc-bridge's interceptTransport(). */
export const contractInterceptor: Interceptor = (next) => async (request) => {
  if (request.service.typeName !== contract.service) {
    throw new ConnectError("Contract interceptor used with the wrong service", Code.FailedPrecondition);
  }
  request.header.set("x-proto-contract", contract.api + "@" + contract.version);
  return next(request);
};
`, quote(s.API), quote(s.Version), quote(s.Service.Name))), nil
}
